/* eslint-disable @typescript-eslint/no-explicit-any */
import { type NextPage } from "next";
import Head from "next/head";

import { useEffect } from "react";

import { Get } from "../backend/tasks/devices";

// import { useStore } from "../backend/tasks/store";

const Home: NextPage = () => {
  // const [store, setStore] = useStore();

  useEffect(() => {
    Get().then((res) => console.log(res) );
  }, []);

  return (
    <>
      <Head>
        <title>Device Viewer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-slate-200 to-slate-300">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[#3995ae]">Device</span> Viewer
          </h1>
        </div>
      </main>
    </>
  );
};

export default Home;
